### ISSUE TITLE
banner/imagem das paginas e dos artigos não aparecem

### ISSUE THREAD

**Issue by lidymonteirowm** [inspiradanacomputacao/inspiradanacomputacao.github.io#32]

**Comment by jcsfbass** [comment]
Resolvido?

**Comment by lidymonteirowm** [comment]
resolvido /o// vou documentar a solução

**Comment by lidymonteirowm** [comment]
ao corrigir a issue #31 corrigiu em algumas paginas e em outras era pq faltava colocar os parametros no documento header, por exemplo:
    image_fullwidth: "banner_principal.jpg"
