### ISSUE TITLE
CSS: Alterar cores do footer

### ISSUE THREAD

**Issue by lidymonteirowm** [inspiradanacomputacao/inspiradanacomputacao.github.io#6]
Vê se fica adequado essas cores, ja que uma parte do footer precisa ser mais clara e outra mais escura
# 8E236B para a parte I do footer onde tem a descrição sobre o site e links
# B5509C  para a parte II do footer onde tem os icones de redes sociais

**Comment by jcsfbass** [comment]
Issue repetida?
